
lab3-test:
  stage: test
  image:
    name: python-tools
    entrypoint: [ "" ]
  script:
    - pip3 install --no-cache-dir -r requirements.txt
    - python3-coverage run -m pytest --verbose ./tests.py
    - find . -type f -name "*.py" | xargs -t python3-coverage report
    - find . -type f -name "*.py" | xargs -t pep8 --ignore=E501,E241
